export enum ErrorMessage {
  USER_ALREADY_EXISTS = '이미 동일한 email을 가진 유저가 존재합니다.',
  NOT_FOUND_USER = '존재하지 않는 유저입니다.',
  USER_PASSWORD_DOESNT_MATCH = '비밀번호가 일치하지 않습니다.',
  USER_PASSWORD_SAME_AS_PREVIOUS = '이전 비밀번호와 동일합니다.',
  DUPLICATE_CATEGORY_NAME_EXISTS = '중복된 카테고리 이름이 존재합니다.',
  NOT_FOUND_CATEGORY = '존재하지 않는 카테고리 입니다.',
  CATEGORY_ALREADY_REGISTERED_IN_THE_BUDGET = '예산에 이미 등록되어 있는 카테고리 입니다.',
  NOT_FOUND_BUDGET = '존재하지 않는 예산 입니다.',
  NOT_BUDGET_REGISTERED_FOR_THAT_CATEGORY = '해당 카테고리로 등록된 예산이 없습니다.',
  ANOTHER_USER_CATEGORY_EXISTS = '다른 유저의 카테고리가 존재합니다.',
  NOT_FOUND_EXPENSE = '존재하지 않는 지출 내역 입니다.',
  NOT_HISTORY_OF_MATCHING_RECOMMEND_BUDGET_TOTAL_AMOUNT = '추천 예산 금액 범위의 내역이 없습니다.',
  NOT_EXPENSE_TODAT = '오늘 지출 내역이 없습니다!',
}
